### ISSUE TITLE
Application shows error message when started

### ISSUE THREAD

**Issue by tataDan** [waleajepe/flutter_bloc_api#1]
When I run the application the Products window appears, but instead of displaying the products it displays the message "An error occurred, please try again".

**Comment by waleajepe** [comment]
Hello tataDan,
I will check this and provide feedback

**Comment by waleajepe** [comment]
> Hello tataDan, I will check this and provide feedback



> When I run the application the Products window appears, but instead of displaying the products it displays the message "An error occurred, please try again".

Hello tataDan,
I will check this and provide feedback
